# Generated by Django 5.0.4 on 2024-04-08 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_course_price_alter_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stamp_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stamp_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего обновления'),
        ),
    ]
