# Generated by Django 5.0.2 on 2024-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на платеж'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Идентификатор сессии'),
        ),
    ]
