# Generated by Django 5.0.2 on 2024-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments_payment_link_payments_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на платеж'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор сессии'),
        ),
    ]
