# Generated by Django 5.0.4 on 2024-04-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на платеж'),
        ),
    ]
