# Generated by Django 5.0.4 on 2024-04-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Идентификатор сессии'),
        ),
    ]
